#!/bin/bash
export IFS=$'\n'

DATE=`date +%Y_%m_%d`
argv=("$@")
CMDNAME=`basename $0`

if [ $# -eq 0 ]; then
	echo "Usage : ${CMDNAME} [dirname]"
	exit 1
fi

## https://qiita.com/hit/items/e95298f689a1ee70ae4a
_pcnt=`pgrep -fo ${CMDNAME} | wc -l`
if [ ${_pcnt} -gt 1 ]; then
	echo "This script has been running now. proc : ${_pcnt}"
	exit 1
fi

for ARG_DIR in ${argv}
do
	TARGET_DIR=`readlink -f ${ARG_DIR}`

	for FILENAME in `find "${TARGET_DIR}" -iname "*.png"`
	do
		mv ${FILENAME} ${FILENAME%%.PNG}.png
		nice -n 19 pngquant -v --ext .png --force --speed 1 --skip-if-larger "${FILENAME}" || continue
	done

	for FILENAME in `find "${TARGET_DIR}" -iname "*.jpg" -or -iname "*.jpeg"`
	do
		nice -n 19 jpegoptim --strip-all --all-progressive "${FILENAME}" || continue
	done

done
