#!/bin/bash
export IFS=$'\n'

DATE=`date +%Y_%m_%d`
argv=("$@")
CMDNAME=`basename $0`

if [ $# -eq 0 ]; then
	echo "Usage : ${CMDNAME} [dirname]"
	exit 1
fi

## https://qiita.com/hit/items/e95298f689a1ee70ae4a
_pcnt=`pgrep -fo ${CMDNAME} | wc -l`
if [ ${_pcnt} -gt 1 ]; then
	echo "This script has been running now. proc : ${_pcnt}"
	exit 1
fi

for ARG_DIR in ${argv}
do
	TARGET_DIR=`readlink -f ${ARG_DIR}`

	for FILENAME in `find "${TARGET_DIR}" -iname "*.png" -or -iname "*.jpg" -or -iname "*.jpeg" -or -iname "*.gif" | sort -h`
	do
		EXTENSION=${FILENAME##*.}
		EXTENSION_LC=`echo ${EXTENSION} | tr '[:upper:]' '[:lower:]'`
		case "$EXTENSION_LC" in 
			"png" )
				nice -n 19 pngquant --verbose --ext .png --force --speed 1 --skip-if-larger "${FILENAME}" || continue
			;;
			"jpg" | "jpeg" )
				nice -n 19 jpegoptim --verbose --strip-all --all-progressive "${FILENAME}" || continue
			;;
			"gif" )
				nice -n 19 gifsicle --verbose --batch --optimize=3 "${FILENAME}" | continue
			;;
		esac
	done
done
